
production: false

title: Emanuel Kluge
description: Beiträge zum Thema JS, HTML, CSS & anderem Kram
baseurl: ""
url: http://www.emanuel-kluge.de/
twitter_username: herschel_r
github_username: herschel666
google_plus: EmanuelKluge
markdown: redcarpet
default_locale: "de"
paginate: 10
paginate_path: "/page/:num/"
lsi: false

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/styles

gems:
  - jekyll-assets
  - jekyll-paginate

exclude: [
  '.htaccess',
  '_assets',
  '_posts.bak',
  'bower.json',
  'package.json',
  'Gemfile',
  'Gemfile.lock',
  'Gruntfile.coffee',
  'userfiles',
  'node_modules'
]
