name: Build and Test and Deploy

on:
  push:
    branches:
      - KillYourMaster
  pull_request:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build & test the application
        env:
          BRANCH: ${{ github.head_ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          npm ci
          npm run test
          npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './_site'
          production-branch: KillYourMaster
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from herschel666/ek-blog-static'
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: ${{ github.head_ref }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
