name: Build and Deploy Microblog

on:
  issues:
    types: [opened, edited, reopened, closed, deleted, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Microblog
        uses: herschel666/microblog-action@beta
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          url: 'https://ekblog.de'
          title: 'ek|blog'
          theme: 'awsm.css'
          date-format: 'd.M.yyyy'
          posts-per-page: 20
          label: 'blog'
          closed: true
          out-dir: '_microblog'
          static-dir: '_assets'
          lang: 'de'
          i18n.next: 'Nächste Artikel'
          i18n.prev: 'Vorherige Artikel'
          i18n.posts: 'Artikel'

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '_microblog'
          production-branch: KillYourMaster
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from microblog action'
          enable-pull-request-comment: false
          enable-commit-comment: false
          netlify-config-path: netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
